config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

// MAINTENANCE - uncomment below line when maintenance
// Router::connect('*', ['controller' => 'Dashboards', 'action' => 'maintenance']);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'dashboards', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Container.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\ORM\TableRegistry;

/**
 * Container Entity
 *
 * @property int $id
 * @property string $name
 * @property int $item_capacity
 * @property int $media_capacity
 * @property int $media_type_id
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 *
 * @property \App\Model\Entity\MediaStock[] $media_stocks
 */
class Container extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'name' => true,
        'item_capacity' => true,
        'media_capacity' => true,
        'media_type_id' => true,
        'created' => true,
        'modified' => true,
        'media_stocks' => true
    ];

    public function _getNameWithType(){
        $mediaTypes = TableRegistry::getTableLocator()->get('MediaTypes')
            ->findById($this->get('media_type_id'))
            ->first();
        return $this->get('name')." [".$mediaTypes->name."]";
    }
}

src/Model/Table/ContainersTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Containers Model
 *
 * @property |\Cake\ORM\Association\BelongsTo $MediaTypes
 * @property \App\Model\Table\MediaStocksTable|\Cake\ORM\Association\HasMany $MediaStocks
 *
 * @method \App\Model\Entity\Container get($primaryKey, $options = [])
 * @method \App\Model\Entity\Container newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Container[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Container|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Container|bool saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Container patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Container[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Container findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class ContainersTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('containers');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('MediaTypes', [
            'foreignKey' => 'media_type_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('MediaStocks', [
            'foreignKey' => 'container_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', 'create');

        $validator
            ->scalar('name')
            ->maxLength('name', 255)
            ->requirePresence('name', 'create')
            ->allowEmptyString('name', false);

        $validator
            ->integer('item_capacity')
            ->requirePresence('item_capacity', 'create')
            ->allowEmptyString('item_capacity', false);

        $validator
            ->integer('media_capacity')
            ->requirePresence('media_capacity', 'create')
            ->allowEmptyString('media_capacity', false);

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['media_type_id'], 'MediaTypes'));

        return $rules;
    }
}

src/Controller/ContainersController.php
<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Containers Controller
 *
 * @property \App\Model\Table\ContainersTable $Containers
 *
 * @method \App\Model\Entity\Container[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ContainersController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $this->paginate = [
            'contain' => ['MediaTypes']];
        $containers = $this->paginate($this->Containers);

        $this->set(compact('containers'));
    }

    /**
     * View method
     *
     * @param string|null $id Container id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $container = $this->Containers->get($id, [
            'contain' => ['MediaStocks', 'MediaTypes']
        ]);

        $this->set('container', $container);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $container = $this->Containers->newEntity();
        if ($this->request->is('post')) {
            $container = $this->Containers->patchEntity($container, $this->request->getData());
            if ($this->Containers->save($container)) {
                $this->Flash->success(__('The container has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The container could not be saved. Please, try again.'));
        }
        $mediatypes = $this->Containers->MediaTypes->find('list', ['limit' => 200]);
        $this->set(compact('container', 'mediatypes'));
    }

    /**
     * Edit method
     *
     * @param string|null $id Container id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $container = $this->Containers->get($id, [
            'contain' => ['MediaTypes']
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $container = $this->Containers->patchEntity($container, $this->request->getData());
            if ($this->Containers->save($container)) {
                $this->Flash->success(__('The container has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The container could not be saved. Please, try again.'));
        }
	    $mediatypes = $this->Containers->MediaTypes->find('list', ['limit' => 200]);
	    $this->set(compact('container', 'mediatypes'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Container id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $container = $this->Containers->get($id);
        if ($this->Containers->delete($container)) {
            $this->Flash->success(__('The container has been deleted.'));
        } else {
            $this->Flash->error(__('The container could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Containers/add.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Container $container
 */
?>
<div class="btn-group">
    <button type="button" class="btn btn-warning btn-raised dropdown-toggle float-right btn-sm" data-toggle="dropdown">
        Actions <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><?= $this->Html->link(__('List Containers'), ['action' => 'index'], ['class'=>"dropdown-item"]) ?></li>
        <li><?= $this->Html->link(__('List Media Stocks'), ['controller' => 'MediaStocks', 'action' => 'index'], ['class'=>"dropdown-item"]) ?></li>
        <li><?= $this->Html->link(__('New Media Stock'), ['controller' => 'MediaStocks', 'action' => 'add'], ['class'=>"dropdown-item"]) ?></li>
    </ul>
</div>
<div class="containers form large-9 medium-8 columns content">
    <?= $this->Form->create($container) ?>
    <fieldset>
        <legend><?= __('Add Container') ?></legend>
        <div class="form-group">
            <?= $this->Form->control('name', ['class' => 'form-control']) ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('item_capacity', ['class' => 'form-control']) ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('media_capacity', ['class' => 'form-control']) ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('media_type_id', ['options' => $mediatypes, 'class' => 'form-control']) ?>
        </div>
    </fieldset>
    <?= $this->Form->button(__('Submit'),['class' => 'btn btn-primary']) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Containers/edit.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Container $container
 */
?>
<div class="dropdown">
    <button type="button" class="btn btn-warning btn-raised dropdown-toggle float-right btn-sm" data-toggle="dropdown">
        Actions <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><?= $this->Form->postLink(
                __('Delete'),
                ['action' => 'delete', $container->id],
                ['confirm' => __('Are you sure you want to delete # {0}?', $container->name), 'class'=>"dropdown-item"]
            )
            ?></li>
        <li><?= $this->Html->link(__('List Containers'), ['action' => 'index'], ['class'=>"dropdown-item"]) ?></li>
        <li><?= $this->Html->link(__('List Media Stocks'), ['controller' => 'MediaStocks', 'action' => 'index'], ['class'=>"dropdown-item"]) ?></li>
        <li><?= $this->Html->link(__('New Media Stock'), ['controller' => 'MediaStocks', 'action' => 'add'], ['class'=>"dropdown-item"]) ?></li>
    </ul>
</div>
<div class="containers form large-9 medium-8 columns content">
    <?= $this->Form->create($container) ?>
    <fieldset>
        <legend><?= __('Edit Container') ?></legend>
        <div class="form-group">
            <?= $this->Form->control('name', ['class' => 'form-control']) ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('item_capacity', ['class' => 'form-control']) ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('media_capacity', ['class' => 'form-control']) ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('media_type_id', ['options' => $mediatypes, 'class' => 'form-control']) ?>
        </div>
    </fieldset>
    <?= $this->Form->button(__('Submit'), ['class' => 'btn btn-primary']) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Containers/index.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Container[]|\Cake\Collection\CollectionInterface $containers
 */
?>
<div class='dropdown'>
    <button type="button" class="btn btn-warning btn-raised dropdown-toggle float-right btn-sm" data-toggle="dropdown">
        Actions <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><?= $this->Html->link(__('New Container'), ['action' => 'add'],['class'=>"dropdown-item"]) ?></li>
        <li><?= $this->Html->link(__('List Media Stocks'), ['controller' => 'MediaStocks', 'action' => 'index'],['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('New Media Stock'), ['controller' => 'MediaStocks', 'action' => 'add'],['class'=>"dropdown-item"]) ?>
        </li>
    </ul>
</div>
<h3><?= __('Containers') ?></h3>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col"><?= $this->Paginator->sort('id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('name') ?></th>
                <th scope="col"><?= $this->Paginator->sort('item_capacity') ?></th>
                <th scope="col"><?= $this->Paginator->sort('media_capacity') ?></th>
                <th scope="col"><?= $this->Paginator->sort('media_type_id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('created') ?></th>
                <th scope="col"><?= $this->Paginator->sort('modified') ?></th>
                <th scope="col" class="actions"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($containers as $container): ?>
            <tr>
                <td><?= $this->Number->format($container->id) ?></td>
                <td><?= h($container->name) ?></td>
                <td><?= $this->Number->format($container->item_capacity) ?></td>
                <td><?= $this->Number->format($container->media_capacity) ?></td>
                <td><?= $container->has('media_type')? $container->media_type->name : '' ?></td>
                <td><?= h($container->created) ?></td>
                <td><?= h($container->modified) ?></td>
                <td class="actions">
                    <div class="btn-group btn-group-toggle">
                        <?= $this->Html->link(__('View'), ['action' => 'view', $container->id], ['class'=> 'btn btn-info btn-sm']) ?>
                        <?= $this->Html->link(__('Edit'), ['action' => 'edit', $container->id], ['class'=> 'btn btn-secondary btn-sm']) ?>
                        <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $container->id], ['confirm' => __('Are you sure you want to delete # {0}?', $container->id), 'class'=> 'btn btn-danger btn-sm']) ?>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="paginator">
    <ul class="pagination">
        <?= $this->Paginator->first('<< ' . __('first')) ?>
        <?= $this->Paginator->prev('< ' . __('previous')) ?>
        <?= $this->Paginator->numbers() ?>
        <?= $this->Paginator->next(__('next') . ' >') ?>
        <?= $this->Paginator->last(__('last') . ' >>') ?>
    </ul>
    <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?>
    </p>
</div>

src/Template/Containers/view.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Container $container
 */
?>
<div class="dropdown">
    <button type="button" class="btn btn-warning btn-raised dropdown-toggle float-right btn-sm" data-toggle="dropdown">
        Actions <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><?= $this->Html->link(__('Edit Container'), ['action' => 'edit', $container->id], ['class'=>"dropdown-item"]) ?> </li>
        <li><?= $this->Form->postLink(__('Delete Container'), ['action' => 'delete', $container->id], ['confirm' => __('Are you sure you want to delete # {0}?', $container->id), 'class'=>"dropdown-item"]) ?> </li>
        <li><?= $this->Html->link(__('List Containers'), ['action' => 'index'], ['class'=>"dropdown-item"]) ?> </li>
        <li><?= $this->Html->link(__('New Container'), ['action' => 'add'], ['class'=>"dropdown-item"]) ?> </li>
        <li><?= $this->Html->link(__('List Media Stocks'), ['controller' => 'MediaStocks', 'action' => 'index'], ['class'=>"dropdown-item"]) ?> </li>
        <li><?= $this->Html->link(__('New Media Stock'), ['controller' => 'MediaStocks', 'action' => 'add'], ['class'=>"dropdown-item"]) ?> </li>
    </ul>
</div>
<div class="containers view large-9 medium-8 columns content">
    <h3><?= h($container->name) ?></h3>
    <table class="table">
        <tr>
            <th scope="row"><?= __('Name') ?></th>
            <td><?= h($container->name) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Id') ?></th>
            <td><?= $this->Number->format($container->id) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Item Capacity') ?></th>
            <td><?= $this->Number->format($container->item_capacity) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Media Capacity') ?></th>
            <td><?= $this->Number->format($container->media_capacity) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Media Type') ?></th>
            <td><?= $container->has('media_type') ? $container->media_type->name : '' ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Created') ?></th>
            <td><?= $this->Time->format(
                    $container->created,
                    'yyyy-MM-dd HH:mm:ss'
                ) ?>
            </td>
        </tr>
        <tr>
            <th scope="row"><?= __('Modified') ?></th>
            <td><?= $this->Time->format(
                    $container->modified,
                    'yyyy-MM-dd HH:mm:ss'
                ) ?>
            </td>
        </tr>
    </table><h4><?= __('Related Media Stocks') ?></h4>
    <div class="table-responsive">
        <?php if (!empty($container->media_stocks)): ?>
        <table class="table table-striped"">
            <thead>
            <tr>
                <th scope="col"><?= $this->Paginator->sort('id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('media_id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('container_id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('batch_id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('user_id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('status') ?></th>
                <th scope="col"><?= $this->Paginator->sort('quantity') ?></th>
                <th scope="col"><?= $this->Paginator->sort('qr_code') ?></th>
                <th scope="col"><?= $this->Paginator->sort('created_by') ?></th>
                <th scope="col"><?= $this->Paginator->sort('created') ?></th>
                <th scope="col"><?= $this->Paginator->sort('modified') ?></th>
                <th scope="col" class="actions"><?= __('Actions') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($container->media_stocks as $mediaStocks): ?>
                <tr>
                    <td><?= h($mediaStocks->id) ?></td>
                    <td><?= h($mediaStocks->media_id) ?></td>
                    <td><?= h($mediaStocks->container_id) ?></td>
                    <td><?= h($mediaStocks->batch_id) ?></td>
                    <td><?= h($mediaStocks->user_id) ?></td>
                    <td><?= h($mediaStocks->status) ?></td>
                    <td><?= h($mediaStocks->quantity) ?></td>
                    <td><?= h($mediaStocks->qr_code) ?></td>
                    <td><?= h($mediaStocks->created_by) ?></td>
                    <td><?= h($mediaStocks->created) ?></td>
                    <td><?= h($mediaStocks->modified) ?></td>
                    <td class="actions">
                        <div class="btn-group btn-group-toggle">
                        <?= $this->Html->link(__('View'), ['controller' => 'MediaStocks', 'action' => 'view', $mediaStocks->id], ['class'=> 'btn btn-info btn-sm']) ?>
                        <?= $this->Html->link(__('Edit'), ['controller' => 'MediaStocks', 'action' => 'edit', $mediaStocks->id], ['class'=> 'btn btn-secondary btn-sm']) ?>
                        <?= $this->Form->postLink(__('Delete'), ['controller' => 'MediaStocks', 'action' => 'delete', $mediaStocks->id],['class'=> 'btn btn-danger btn-sm'], ['confirm' => __('Are you sure you want to delete # {0}?', $mediaStocks->id)]) ?>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?php endif; ?>
    </div>


</div>