config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

// MAINTENANCE - uncomment below line when maintenance
// Router::connect('*', ['controller' => 'Dashboards', 'action' => 'maintenance']);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'dashboards', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/MediaStock.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * MediaStock Entity
 *
 * @property int $id
 * @property int $media_id
 * @property int $container_id
 * @property int $batch_id
 * @property int $assigned_user_id
 * @property int $container_quantity
 * @property int|null $autoclave
 * @property int $created_user_id
 * @property \Cake\I18n\FrozenTime|null $completed
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 *
 * @property \App\Model\Entity\Media $media
 * @property \App\Model\Entity\Container $container
 * @property \App\Model\Entity\Batch $batch
 * @property \App\Model\Entity\User $user
 * @property \App\Model\Entity\User $Assign
 * @property \App\Model\Entity\User $Generate
 */
class MediaStock extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'media_id' => true,
        'container_id' => true,
        'batch_id' => true,
        'assigned_user_id' => true,
        'container_quantity' => true,
        'autoclave' => true,
        'created_user_id' => true,
        'completed' => true,
        'created' => true,
        'modified' => true,
        'media' => true,
        'container' => true,
        'batch' => true,
        'user' => true,
        'CreatedUsers' => true
    ];
}

src/Model/Entity/User.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;
use Cake\Auth\DefaultPasswordHasher;

/**
 * User Entity
 *
 * @property int $id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property string $password
 * @property string $employment_number
 * @property string $user_type
 * @property |null $profile_image
 * @property bool|null $active
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 *
 * @property \App\Model\Entity\MediaStock[] $media_stocks
 * @property \App\Model\Entity\Order[] $orders
 */
class User extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        'first_name' => true,
        'last_name' => true,
        'email' => true,
        'password' => true,
        'employment_number' => true,
        'user_type' => true,
        'profile_image' => true,
        'active' => true,
        'created' => true,
        'modified' => true,
        'media_stocks' => true,
        'orders' => true
    ];

    /**
     * Fields that are excluded from JSON versions of the entity.
     *
     * @var array
     */
    protected $_hidden = [
        'password'
    ];

	protected function _setPassword($value)
	{
		if (strlen($value)) {
			$hasher = new DefaultPasswordHasher();
			return $hasher->hash($value);
		}
	}

    protected function _setPasswordConfirm($value)
    {
        if (strlen($value)) {
            $hasher = new DefaultPasswordHasher();
            return $hasher->hash($value);
        }
    }

	public function _getFullName(){
		return $this->get('first_name')." ".$this->get('last_name');
    }
    
    /**
     * check for user authentication
     * @param array|null $types.
     * @return bool
     */
    public function isAuthorized($types){
        foreach($types as $type){
            if ($this->user_type == $type){
                return true;
            }
		}
		return false;
    }
}

src/Model/Table/MediaStocksTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * MediaStocks Model
 *
 * @property \App\Model\Table\MediasTable|\Cake\ORM\Association\BelongsTo $Medias
 * @property \App\Model\Table\ContainersTable|\Cake\ORM\Association\BelongsTo $Containers
 * @property \App\Model\Table\BatchesTable|\Cake\ORM\Association\BelongsTo $Batches
 * @property \App\Model\Table\UsersTable|\Cake\ORM\Association\BelongsTo $Users
 * @property \App\Model\Table\UsersTable|\Cake\ORM\Association\BelongsTo $CreatedUsers
 *
 * @method \App\Model\Entity\MediaStock get($primaryKey, $options = [])
 * @method \App\Model\Entity\MediaStock newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\MediaStock[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\MediaStock|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\MediaStock|bool saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\MediaStock patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\MediaStock[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\MediaStock findOrCreate($search, callable $callback = null, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class MediaStocksTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('media_stocks');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Medias', [
            'foreignKey' => 'media_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Containers', [
            'foreignKey' => 'container_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Batches', [
            'foreignKey' => 'batch_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Users', [
            'foreignKey' => 'assigned_user_id',
            'joinType' => 'INNER'
        ]);
        // $this->belongsTo('Users', [
        //     'foreignKey' => 'created_user_id',
        //     'joinType' => 'INNER'
        // ]);

        $this->belongsTo('CreatedUsers', [
            'className' => 'Users',
            'foreignKey' => 'created_user_id',
            'joinType' => 'INNER',
            'propertyName' => 'CreatedUsers'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', 'create');

        $validator
            ->integer('container_quantity')
            ->requirePresence('container_quantity', 'create')
            ->allowEmptyString('container_quantity', false);

        $validator
            ->integer('autoclave')
            ->allowEmptyString('autoclave');

        $validator
            ->dateTime('completed')
            ->allowEmptyDateTime('completed');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['media_id'], 'Medias'));
        $rules->add($rules->existsIn(['container_id'], 'Containers'));
        $rules->add($rules->existsIn(['batch_id'], 'Batches'));
        $rules->add($rules->existsIn(['assigned_user_id'], 'Users'));
        $rules->add($rules->existsIn(['created_user_id'], 'Users'));

        return $rules;
    }
}

src/Template/MediaStocks/add.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\MediaStock $mediaStock
 */
?>
<div class="dropdown">
    <button type="button" class="btn btn-warning btn-raised dropdown-toggle float-right btn-sm" data-toggle="dropdown">
        Actions <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><?= $this->Html->link(__('List Media Stocks'), ['action' => 'index'], ['class'=>"dropdown-item"]) ?></li>
        <li><?= $this->Html->link(__('List Medias'), ['controller' => 'Medias', 'action' => 'index'], ['class'=>"dropdown-item"]) ?></li>
        <li><?= $this->Html->link(__('New Media'), ['controller' => 'Medias', 'action' => 'add'], ['class'=>"dropdown-item"]) ?></li>
        <li><?= $this->Html->link(__('List Containers'), ['controller' => 'Containers', 'action' => 'index'], ['class'=>"dropdown-item"]) ?></li>
        <li><?= $this->Html->link(__('New Container'), ['controller' => 'Containers', 'action' => 'add'], ['class'=>"dropdown-item"]) ?></li>
    </ul>
</div>
<div class="mediaStocks form large-9 medium-8 columns content">
    <?= $this->Form->create($mediaStock) ?>
    <fieldset>
        <legend><?= __('Add Media Stock') ?></legend>
        <div class="form-group">
            <?= $this->Form->control('media_id', ['options' => $medias, 'class' => 'form-control']); ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('container_id', ['options' => $containers, 'class' => 'form-control']);?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('assigned_user_id', ['options' => $users, 'class' => 'form-control']); ?>
        </div>

        <div class="form-group">
            <?= $this->Form->control('container_quantity', ['class' => 'form-control']); ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('autoclave', ['class' => 'form-control']);?>
        </div>
    </fieldset>
    <?= $this->Form->button(__('Submit'),['class' => 'btn btn-primary']) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/MediaStocks/edit.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\MediaStock $mediaStock
 */
?>
<div class="dropdown">
    <button type="button" class="btn btn-warning btn-raised dropdown-toggle float-right btn-sm" data-toggle="dropdown">
        Actions <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><?= $this->Form->postLink(
                __('Delete'),
                ['action' => 'delete', $mediaStock->id],
                ['confirm' => __('Are you sure you want to delete # {0}?', $mediaStock->id), 'class' => "dropdown-item"]
            )
        ?>
        </li>
        <li><?= $this->Html->link(__('List Media Stocks'), ['action' => 'index'], ['class'=>"dropdown-item"]) ?></li>
        <li><?= $this->Html->link(__('List Medias'), ['controller' => 'Medias', 'action' => 'index'], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('New Media'), ['controller' => 'Medias', 'action' => 'add'], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('List Containers'), ['controller' => 'Containers', 'action' => 'index'], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('New Container'), ['controller' => 'Containers', 'action' => 'add'], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('List Batches'), ['controller' => 'Batches', 'action' => 'index'], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('New Batch'), ['controller' => 'Batches', 'action' => 'add'], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('List Users'), ['controller' => 'Users', 'action' => 'index'], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('New User'), ['controller' => 'Users', 'action' => 'add'], ['class'=>"dropdown-item"]) ?>
        </li>
    </ul>
</div>
<div class="mediaStocks form large-9 medium-8 columns content">
    <?= $this->Form->create($mediaStock) ?>
    <fieldset>
        <legend><?= __('Edit Media Stock') ?></legend>
        <div class="form-group">
            <?= $this->Form->control('media_id', ['options' => $medias, 'class' => 'form-control']) ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('container_id', ['options' => $containers, 'class' => 'form-control']) ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('batch_id', ['disabled' => 'disabled', 'class' => 'form-control']) ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('assigned_user_id', ['options' => $users, 'class' => 'form-control']) ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('container_quantity', ['class' => 'form-control']) ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('autoclave', ['class' => 'form-control']) ?>
        </div>
        <div class="form-group">
            <?= $this->Form->control('created_user_id', ['options' => $users, 'class' => 'form-control', 'disabled' => 'disabled']) ?>
        </div>
    </fieldset>
    <?= $this->Form->button(__('Submit'),['class' => 'btn btn-primary']) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/MediaStocks/index.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\MediaStock[]|\Cake\Collection\CollectionInterface $mediaStocks
 */
?>
<div class="dropdown">
    <button type="button" class="btn btn-warning btn-raised dropdown-toggle float-right btn-sm" data-toggle="dropdown">
        Actions <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><?= $this->Html->link(__('New Media Stock'), ['action' => 'add'], ['class'=>"dropdown-item"]) ?></li>
        <li><?= $this->Html->link(__('List Medias'), ['controller' => 'Medias', 'action' => 'index'], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('New Media'), ['controller' => 'Medias', 'action' => 'add'], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('List Containers'), ['controller' => 'Containers', 'action' => 'index'], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('New Container'), ['controller' => 'Containers', 'action' => 'add'], ['class'=>"dropdown-item"]) ?>
        </li>
    </ul>
</div>
<div class="mediaStocks index large-9 medium-8 columns content">
    <h3><?= __('Media Stocks') ?></h3>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col"><?= $this->Paginator->sort('id') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('media_id') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('container_id') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('batch_id') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('assigned_user_id') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('container_quantity') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('autoclave') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('created_user_id') ?></th>
                    <th scope="col"><?= $this->Paginator->sort('created') ?></th>
                    <th scope="col" class="actions"><?= __('Actions') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($mediaStocks as $mediaStock): ?>
                <tr>
                    <td><?= $this->Number->format($mediaStock->id) ?></td>
                    <td><?= $mediaStock->has('media') ? $this->Html->link($mediaStock->media->name, ['controller' => 'Medias', 'action' => 'view', $mediaStock->media->id]) : '' ?>
                    </td>
                    <td><?= $mediaStock->has('container') ? $this->Html->link($mediaStock->container->name, ['controller' => 'Containers', 'action' => 'view', $mediaStock->container->id]) : '' ?>
                    </td>
                    <td><?= $mediaStock->has('batch') ? $this->Html->link($mediaStock->batch->id, ['controller' => 'Batches', 'action' => 'view', $mediaStock->batch->id]) : '' ?>
                    </td>
                    <td><?= $mediaStock->has('user') ? $mediaStock->user->first_name : '' ?></td>
                    <td><?= $this->Number->format($mediaStock->container_quantity) ?></td>
                    <td><?= $this->Number->format($mediaStock->autoclave) ?></td>
                    <td><?= $mediaStock->has('CreatedUsers') ? $mediaStock->CreatedUsers->first_name : '' ?></td>
                    <td><?= h($mediaStock->created) ?></td>
                    <td class="actions">
                        <div class="btn-group btn-group-toggle">
                            <?= $this->Html->link(__('View'), ['action' => 'view', $mediaStock->id], ['class'=> 'btn btn-info btn-sm']) ?>
                            <?= $this->Html->link(__('Edit'), ['action' => 'edit', $mediaStock->id], ['class'=> 'btn btn-secondary btn-sm']) ?>
                            <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $mediaStock->id], ['class'=> 'btn btn-danger btn-sm'], ['confirm' => __('Are you sure you want to delete # {0}?', $mediaStock->id)]) ?>
                        </div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?>
        </p>
    </div>
</div>

src/Template/MediaStocks/view.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\MediaStock $mediaStock
 */
?>
<div class="dropdown">
    <button type="button" class="btn btn-warning btn-raised dropdown-toggle float-right btn-sm" data-toggle="dropdown">
        Actions <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><?= $this->Html->link(__('Edit Media Stock'), ['action' => 'edit', $mediaStock->id], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Form->postLink(__('Delete Media Stock'), ['action' => 'delete', $mediaStock->id], ['confirm' => __('Are you sure you want to delete # {0}?'), 'class' => "dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('List Media Stocks'), ['action' => 'index'], ['class'=>"dropdown-item"]) ?> </li>
        <li><?= $this->Html->link(__('New Media Stock'), ['action' => 'add'], ['class' => "dropdown-item"]) ?> </li>
        <li><?= $this->Html->link(__('List Medias'), ['controller' => 'Medias', 'action' => 'index'], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('New Media'), ['controller' => 'Medias', 'action' => 'add'], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('List Containers'), ['controller' => 'Containers', 'action' => 'index'], ['class'=>"dropdown-item"]) ?>
        </li>
        <li><?= $this->Html->link(__('New Container'), ['controller' => 'Containers', 'action' => 'add'], ['class'=>"dropdown-item"]) ?>
        </li>
    </ul>
</div>
<div class="mediaStocks view large-9 medium-8 columns content">
    <h3><?= h($mediaStock->id) ?></h3>
    <table class="table">
        <tr>
            <th scope="row"><?= __('Media') ?></th>
            <td><?= $mediaStock->has('media') ? $this->Html->link($mediaStock->media->name, ['controller' => 'Medias', 'action' => 'view', $mediaStock->media->id]) : '' ?>
            </td>
        </tr>
        <tr>
            <th scope="row"><?= __('Container') ?></th>
            <td><?= $mediaStock->has('container') ? $this->Html->link($mediaStock->container->name, ['controller' => 'Containers', 'action' => 'view', $mediaStock->container->id]) : '' ?>
            </td>
        </tr>
        <tr>
            <th scope="row"><?= __('Batch') ?></th>
            <td><?= $mediaStock->has('batch') ? $this->Html->link($mediaStock->batch->id, ['controller' => 'Batches', 'action' => 'view', $mediaStock->batch->id]) : '' ?>
            </td>
        </tr>
        <tr>
            <th scope="row"><?= __('Id') ?></th>
            <td><?= $this->Number->format($mediaStock->id) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Assigned User') ?></th>
            <td><?= $mediaStock->has('user') ? $mediaStock->user->full_name : '' ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Container Quantity') ?></th>
            <td><?= $this->Number->format($mediaStock->container_quantity) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Autoclave') ?></th>
            <td><?= $this->Number->format($mediaStock->autoclave) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Created User') ?></th>
            <td><?= $mediaStock->has('CreatedUsers') ? $mediaStock->CreatedUsers->full_name : '' ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Completed') ?></th>
            <td><?= $mediaStock->completed ? 'Yes' : 'No' ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Created') ?></th>
            <td><?= h($mediaStock->created) ?></td>
        </tr>
        <tr>
            <th scope="row"><?= __('Modified') ?></th>
            <td><?= h($mediaStock->modified) ?></td>
        </tr>
    </table>
</div>
    <!-- Print label -->
<div class="row">
    <div class="col-12">
        <button class="btn btn-outline-primary print"
                data-product-id="<?= $mediaStock->id ?>"
                data-loading-text="<i class='glyphicon glyphicon-cog gly-spin'></i> Printing...">
            Print label
        </button>
    </div>
</div>
<script>
    $(document).ready(function($){
        $('button.print').on('click', function(event) {
            event.preventDefault();
            if (confirm('Are you sure you want reprint label?')){
                // Start animation to show progress
                $(this).toggleClass("btn-disabled");
                $(this).prop('disabled', true);
                $(this).attr('disabled', 'disabled');
                $(this).button('loading');
                $.get('/media-stocks/label/' + $(this).attr('data-product-id'), function (response) {
                    response = JSON.parse(response);
                    // Get the button that signaled
                    let btn = $("button.print[data-product-id='" + response.id + "']");
                    $(btn).button('reset');
                    $(btn).toggleClass("btn-disabled");
                    $(btn).prop('disabled', false);
                    $(btn).removeAttr('disabled');
                    $(btn).parent().append("<div class=\"message alert "+ response.alert+"\" role=\"alert\" onclick=\"this.classList.add('hidden')\">" + response.message + "</div>");
                });
            }
        });

    });
</script>